site_url: http://www.needplus.love   # 替换为你的域名
extra:
  cname: needplus.love  # 可选，某些主题需要


# 最低必需配置
site_name: My Site
nav:
    - Home: index.html  # 确保导航指向index.html

# 确保没有index.md，避免冲突
use_directory_urls: false  # 禁用目录URL，直接访问index.html
